name: Download from Spotify 2

on:
  # Manual trigger
  workflow_dispatch:

jobs:
  run-vless:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget build-essential

      # Step 3: Clone and build spotifydownload
      - name: Clone spotifydownload repository
        run: |
          git clone https://github.com/schollz/spotifydownload.git
          cd spotifydownload
          go build -o spotifydownload .

      # Step 4: Add spotifydownload to PATH
      - name: Add to PATH
        run: echo "${{ github.workspace }}/spotifydownload" >> $GITHUB_PATH

      # Step 5: Download Spotify playlist
      - name: Download playlist
        run: spotifydownload -playlist https://open.spotify.com/playlist/3dfaSDUbwFRu2IDx90SZte?si=mU60aGiZSBy15Ci6L1A2Zg

      # Step 6: List downloaded files
      - name: List downloaded files
        run: ls -lh *.mp3

      # Step 7: Upload MP3 files as artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Songs
          path: "*.mp3"
